/**
 * 🎯 COMPREHENSIVE API → PERMISSION MAPPING
 *
 * This file contains the complete mapping of all API endpoints to their required permissions.
 * This is the foundation for intelligent dependency resolution.
 *
 * Generated by analyzing all route files in the server/routes directory.
 */

const API_PERMISSION_MAP = {
  // ========================================
  // AUTHENTICATION ROUTES (/api/auth)
  // ========================================
  "POST /api/auth/register-owner": [], // Public endpoint
  "POST /api/auth/register-user": [], // Requires token but no specific permission
  "POST /api/auth/login": [], // Public endpoint
  "GET /api/auth/hostels": [], // Requires token only
  "GET /api/auth/hostels/all": [], // Requires token only
  "POST /api/auth/set-active-hostel": [], // Requires token only
  "PUT /api/auth/profile": [], // Requires token only
  "PUT /api/auth/change-password": [], // Requires token only

  // ========================================
  // ADMIN ROUTES (/api/admin)
  // ========================================
  "GET /api/admin/stats": ["view_hostel_stats"],
  "GET /api/admin/hostels": ["hostel_read"],

  // Room Management
  "GET /api/admin/rooms": ["room_read"],
  "POST /api/admin/rooms": ["room_create"],
  "PUT /api/admin/rooms/:id": ["room_update"],
  "DELETE /api/admin/rooms/:id": ["room_delete"],

  // Student Management
  "GET /api/admin/students": ["student_read"],
  "POST /api/admin/students": ["student_create"],
  "PUT /api/admin/students/:id": ["student_update"],
  "DELETE /api/admin/students/:id": ["student_delete"],
  "GET /api/admin/students/export": ["export_student_data"],

  // Staff Management
  "GET /api/admin/staff": ["staff_read"],
  "POST /api/admin/staff": ["staff_create"],
  "PUT /api/admin/staff/:id": ["staff_update"],
  "DELETE /api/admin/staff/:id": ["staff_delete"],

  // Room Allocation (Updated to use new permission names)
  "POST /api/admin/allocate-room": ["room_allocation_create"],
  "PUT /api/admin/deallocate-room/:allocationId": ["room_allocation_delete"],

  // Complaint Management (Split CRUD)
  "GET /api/admin/complaints": ["complaint_read"],
  "PUT /api/admin/complaints/:id": ["complaint_update"],
  "PUT /api/admin/complaints/:id/resolve": ["complaint_update"],

  // Visitor Log Management (Updated to new permissions)
  "GET /api/admin/visitor-logs": ["visitor_read"],
  "POST /api/admin/visitor-logs": ["visitor_create"],
  "PUT /api/admin/visitor-logs/:id/checkout": ["visitor_update"],
  "PUT /api/admin/visitor-logs/:id": ["visitor_update"],
  "DELETE /api/admin/visitor-logs/:id": ["visitor_delete"],
  "GET /api/admin/visitor-stats": ["visitor_read"],
  "GET /api/admin/visitor-logs/export": ["export_visitor_data"],

  // ========================================
  // HOSTEL ROUTES (/api/hostels)
  // ========================================

  // Base Hostel Routes
  "GET /api/hostels": ["hostel_read"],
  "POST /api/hostels": ["hostel_create"],

  // Hostel-Specific Routes
  "GET /api/hostels/:hostelId": ["hostel_read"],
  "PUT /api/hostels/:hostelId": ["hostel_update"],
  "DELETE /api/hostels/:hostelId": ["hostel_delete"],

  // Dashboard Routes
  "GET /api/hostels/:hostelId/dashboard": ["hostel_read"],
  "GET /api/hostels/:hostelId/stats": ["view_hostel_stats"],

  // Visitor Management (Updated to new permission structure)
  "GET /api/hostels/:hostelId/visitors": ["visitor_read"],
  "POST /api/hostels/:hostelId/visitors": ["visitor_create"],
  "PUT /api/hostels/:hostelId/visitors/:visitorId": ["visitor_update"],
  "DELETE /api/hostels/:hostelId/visitors/:visitorId": ["visitor_delete"],
  "POST /api/hostels/:hostelId/visitors/:visitorId/checkout": [
    "visitor_update",
  ],
  "GET /api/hostels/:hostelId/visitors/export": ["export_visitor_data"],

  // Student Management (Split CRUD)
  "GET /api/hostels/:hostelId/students": ["student_read"],
  "POST /api/hostels/:hostelId/students": ["student_create"],
  "PUT /api/hostels/:hostelId/students/:studentId": ["student_update"],
  "DELETE /api/hostels/:hostelId/students/:studentId": ["student_delete"],
  "GET /api/hostels/:hostelId/students/export": ["export_student_data"],

  // Complaint Management
  "GET /api/hostels/:hostelId/complaints": ["complaint_read"],
  "POST /api/hostels/:hostelId/complaints": ["complaint_create"],
  "POST /api/hostels/:hostelId/complaints/:complaintId/resolve": [
    "complaint_update",
  ],
  "PUT /api/hostels/:hostelId/complaints/:complaintId/status": [
    "complaint_update",
  ],
  "DELETE /api/hostels/:hostelId/complaints/:complaintId": ["complaint_delete"],
  "GET /api/hostels/:hostelId/complaints/export": ["export_complaint_data"],

  // Room Management (Split CRUD)
  "GET /api/hostels/:hostelId/rooms": ["room_read"],
  "POST /api/hostels/:hostelId/rooms": ["room_create"],
  "PUT /api/hostels/:hostelId/rooms/:roomId": ["room_update"],
  "DELETE /api/hostels/:hostelId/rooms/:roomId": ["room_delete"],
  "GET /api/hostels/:hostelId/rooms/:roomId/students": ["room_allocation_read"],
  "GET /api/hostels/:hostelId/rooms/export": ["export_room_data"],

  // Room Allocation (Updated to new permission names)
  "POST /api/hostels/:hostelId/room-allocations": ["room_allocation_create"],
  "DELETE /api/hostels/:hostelId/room-allocations/:allocationId": [
    "room_allocation_delete",
  ],

  // Warden Management
  "GET /api/hostels/:hostelId/wardens": ["staff_read"],
  "POST /api/hostels/:hostelId/wardens": ["staff_create"],
  "PUT /api/hostels/:hostelId/wardens/:wardenId": ["staff_update"],
  "DELETE /api/hostels/:hostelId/wardens/:wardenId": ["staff_delete"],

  // Staff Management
  "GET /api/hostels/:hostelId/staff": ["staff_read"],
  "POST /api/hostels/:hostelId/staff": ["staff_create"],
  "PUT /api/hostels/:hostelId/staff/:staffId": ["staff_update"],
  "DELETE /api/hostels/:hostelId/staff/:staffId": ["staff_delete"],
  "PATCH /api/hostels/:hostelId/staff/:staffId/status": ["staff_update"],
  "GET /api/hostels/:hostelId/staff/export": ["export_staff_data"],

  // ========================================
  // RBAC ROUTES (/api/rbac)
  // ========================================

  // User Permission Routes
  "GET /api/rbac/user-permissions": [], // Requires token only
  "POST /api/rbac/check-permission": [], // Requires token only
  "POST /api/rbac/check-any-permission": [], // Requires token only
  "POST /api/rbac/check-all-permissions": [], // Requires token only

  // ========================================
  // STUDENT ROUTES (/api/student)
  // ========================================
  // Student self-service (canonical permissions)
  "GET /api/student/dashboard": ["hostel_read"], // dashboard access now tied to hostel visibility
  "GET /api/student/profile": ["view_profile"],
  "PUT /api/student/profile": ["manage_profile"],
  "GET /api/student/room": ["view_student_rooms"],
  "POST /api/student/complaints": ["complaint_create"],
  "GET /api/student/complaints": ["complaint_read"],
  "GET /api/student/complaints/:id": ["complaint_read"],
  "PUT /api/student/complaints/:id": ["complaint_update"],
  "DELETE /api/student/complaints/:id": ["complaint_delete"],
  "GET /api/student/visitor-logs": ["visitor_read"],
  "POST /api/student/visitor-logs": ["visitor_create"],
  "PUT /api/student/visitor-logs/:id": ["visitor_update"],
  "DELETE /api/student/visitor-logs/:id": ["visitor_delete"],
  "PUT /api/student/visitor-logs/:id/checkout": ["visitor_update"],

  // ========================================
  // SUPERADMIN ROUTES (/api/superadmin)
  // ========================================
  "POST /api/superadmin/login": [], // Public endpoint
  "GET /api/superadmin/dashboard": ["manage_system"],
  "GET /api/superadmin/billing-overview": ["manage_billing"],
  "POST /api/superadmin/owners": ["manage_owners"],
  "POST /api/superadmin/hostels": ["manage_all_hostels"],
  "GET /api/superadmin/hostels": ["manage_all_hostels"],
  "GET /api/superadmin/hostels/:id": ["manage_all_hostels"],
  "GET /api/superadmin/hostels/:id/students": ["manage_all_hostels"],
  "PUT /api/superadmin/hostels/:id/plan": ["manage_all_hostels"],
  "PUT /api/superadmin/hostels/:id/status": ["manage_all_hostels"],
  "PUT /api/superadmin/hostels/:id/billing": ["manage_billing"],
  "DELETE /api/superadmin/hostels/:id": ["manage_all_hostels"],
  "GET /api/superadmin/hostels-by-region": ["view_system_stats"],
};

/**
 * Get permissions required for a specific API endpoint
 * @param {string} method - HTTP method (GET, POST, PUT, DELETE, etc.)
 * @param {string} path - API path (e.g., '/api/hostels/:hostelId/students')
 * @returns {Array<string>} Array of required permission names
 */
function getApiPermissions(method, path) {
  const key = `${method.toUpperCase()} ${path}`;
  return API_PERMISSION_MAP[key] || [];
}

/**
 * Get all API endpoints that require a specific permission
 * @param {string} permission - Permission name
 * @returns {Array<string>} Array of API endpoint keys
 */
function getApisForPermission(permission) {
  return Object.keys(API_PERMISSION_MAP).filter((api) =>
    API_PERMISSION_MAP[api].includes(permission)
  );
}

/**
 * Get all unique permissions used in the API
 * @returns {Array<string>} Array of unique permission names
 */
function getAllApiPermissions() {
  const permissions = new Set();
  Object.values(API_PERMISSION_MAP).forEach((apiPermissions) => {
    apiPermissions.forEach((permission) => permissions.add(permission));
  });
  return Array.from(permissions).sort();
}

/**
 * Get API endpoints grouped by permission category
 * @returns {Object} Object with permission categories as keys
 */
function getApisByCategory() {
  const categories = {
    hostel_read: [],
    room_read: [],
    student_read: [],
    complaint_read: [],
    visitor_read: [],
    staff_management: [],
    rbac_management: [],
    student_self_service: [],
    superadmin_management: [],
  };

  Object.entries(API_PERMISSION_MAP).forEach(([api, permissions]) => {
    if (api.includes("/hostels") && !api.includes("/rbac/")) {
      if (api.includes("/rooms")) {
        categories.room_management.push(api);
      } else if (api.includes("/students")) {
        categories.student_management.push(api);
      } else if (api.includes("/complaints")) {
        categories.complaint_management.push(api);
      } else if (api.includes("/visitors")) {
        categories.visitor_management.push(api);
      } else if (api.includes("/wardens") || api.includes("/staff")) {
        categories.staff_management.push(api);
      } else {
        categories.hostel_management.push(api);
      }
    } else if (api.includes("/rbac/")) {
      categories.rbac_management.push(api);
    } else if (api.includes("/student/")) {
      categories.student_self_service.push(api);
    } else if (api.includes("/superadmin/")) {
      categories.superadmin_management.push(api);
    }
  });

  return categories;
}

module.exports = {
  API_PERMISSION_MAP,
  getApiPermissions,
  getApisForPermission,
  getAllApiPermissions,
  getApisByCategory,
};
