/**
 * 🎯 COMPREHENSIVE API → PERMISSION MAPPING
 * 
 * This file contains the complete mapping of all API endpoints to their required permissions.
 * This is the foundation for intelligent dependency resolution.
 * 
 * Generated by analyzing all route files in the server/routes directory.
 */

const API_PERMISSION_MAP = {
  // ========================================
  // AUTHENTICATION ROUTES (/api/auth)
  // ========================================
  'POST /api/auth/register-owner': [], // Public endpoint
  'POST /api/auth/register-user': [], // Requires token but no specific permission
  'POST /api/auth/login': [], // Public endpoint
  'GET /api/auth/hostels': [], // Requires token only
  'GET /api/auth/hostels/all': [], // Requires token only
  'POST /api/auth/set-active-hostel': [], // Requires token only
  'PUT /api/auth/profile': [], // Requires token only
  'PUT /api/auth/change-password': [], // Requires token only

  // ========================================
  // ADMIN ROUTES (/api/admin)
  // ========================================
  'GET /api/admin/stats': ['hostel_stats_read'],
  'GET /api/admin/hostels': ['hostel_read'],
  
  // Room Management
  'GET /api/admin/rooms': ['room_read'],
  'POST /api/admin/rooms': ['room_create'],
  'PUT /api/admin/rooms/:id': ['room_update'],
  'DELETE /api/admin/rooms/:id': ['room_delete'],
  
  // Student Management
  'GET /api/admin/students': ['student_read'],
  'POST /api/admin/students': ['student_create'],
  'PUT /api/admin/students/:id': ['student_update'],
  'DELETE /api/admin/students/:id': ['student_delete'],
  
  // Warden Management
  'GET /api/admin/wardens': ['warden_read'],
  'POST /api/admin/wardens': ['warden_create'],
  'PUT /api/admin/wardens/:id': ['warden_update'],
  'DELETE /api/admin/wardens/:id': ['warden_delete'],
  
  // Room Allocation
  'POST /api/admin/allocate-room': ['room_allocate'],
  'PUT /api/admin/deallocate-room/:allocationId': ['room_deallocate'],
  
  // Complaint Management
  'GET /api/admin/complaints': ['complaint_read'],
  'PUT /api/admin/complaints/:id': ['complaint_update'],
  'PUT /api/admin/complaints/:id/resolve': ['complaint_update'],
  
  // Visitor Log Management
  'GET /api/admin/visitor-logs': ['visitor_read'],
  'POST /api/admin/visitor-logs': ['visitor_create'],
  'PUT /api/admin/visitor-logs/:id/checkout': ['visitor_checkout'],
  'PUT /api/admin/visitor-logs/:id': ['visitor_update'],
  'DELETE /api/admin/visitor-logs/:id': ['visitor_delete'],
  'GET /api/admin/visitor-stats': ['visitor_stats_read'],
  'GET /api/admin/visitor-logs/export': ['visitor_export'],

  // ========================================
  // HOSTEL ROUTES (/api/hostels)
  // ========================================
  
  // Base Hostel Routes
  'GET /api/hostels': ['hostel_read'],
  'POST /api/hostels': ['hostel_update'],
  
  // Hostel-Specific Routes
  'GET /api/hostels/:hostelId': ['hostel_read'],
  'PUT /api/hostels/:hostelId': ['hostel_update'],
  'DELETE /api/hostels/:hostelId': ['hostel_update'],
  
  // Dashboard Routes
  'GET /api/hostels/:hostelId/dashboard': ['hostel_read'],
  'GET /api/hostels/:hostelId/stats': ['hostel_read'],
  
  // Visitor Management
  'GET /api/hostels/:hostelId/visitors': ['visitor_read'],
  'POST /api/hostels/:hostelId/visitors': ['visitor_create'],
  'PUT /api/hostels/:hostelId/visitors/:visitorId': ['visitor_update'],
  'DELETE /api/hostels/:hostelId/visitors/:visitorId': ['visitor_update'],
  'POST /api/hostels/:hostelId/visitors/:visitorId/checkout': ['visitor_checkout'],
  
  // Student Management
  'GET /api/hostels/:hostelId/students': ['student_read'],
  'POST /api/hostels/:hostelId/students': ['student_update'],
  'PUT /api/hostels/:hostelId/students/:studentId': ['student_update'],
  'DELETE /api/hostels/:hostelId/students/:studentId': ['student_update'],
  
  // Complaint Management
  'GET /api/hostels/:hostelId/complaints': ['complaint_read'],
  'POST /api/hostels/:hostelId/complaints': ['complaint_create'],
  'POST /api/hostels/:hostelId/complaints/:complaintId/resolve': ['complaint_update'],
  'PUT /api/hostels/:hostelId/complaints/:complaintId/status': ['complaint_update'],
  'DELETE /api/hostels/:hostelId/complaints/:complaintId': ['complaint_delete'],
  
  // Room Management
  'GET /api/hostels/:hostelId/rooms': ['room_read'],
  'POST /api/hostels/:hostelId/rooms': ['room_update'],
  'PUT /api/hostels/:hostelId/rooms/:roomId': ['room_update'],
  'DELETE /api/hostels/:hostelId/rooms/:roomId': ['room_update'],
  'GET /api/hostels/:hostelId/rooms/:roomId/students': ['room_allocation_read'],
  
  // Room Allocation
  'POST /api/hostels/:hostelId/room-allocations': ['room_allocate'],
  'DELETE /api/hostels/:hostelId/room-allocations/:allocationId': ['room_deallocate'],
  
  // Warden Management
  'GET /api/hostels/:hostelId/wardens': ['warden_read'],
  'POST /api/hostels/:hostelId/wardens': ['warden_update'],
  'PUT /api/hostels/:hostelId/wardens/:wardenId': ['warden_update'],
  'DELETE /api/hostels/:hostelId/wardens/:wardenId': ['warden_update'],
  
  // Staff Management
  'GET /api/hostels/:hostelId/staff': ['role_read'],
  'POST /api/hostels/:hostelId/staff': ['role_update'],
  'PUT /api/hostels/:hostelId/staff/:staffId': ['role_update'],
  'DELETE /api/hostels/:hostelId/staff/:staffId': ['role_update'],
  'PATCH /api/hostels/:hostelId/staff/:staffId/status': ['role_update'],

  // ========================================
  // RBAC ROUTES (/api/rbac)
  // ========================================
  
  // User Permission Routes
  'GET /api/rbac/user-permissions': [], // Requires token only
  'POST /api/rbac/check-permission': [], // Requires token only
  'POST /api/rbac/check-any-permission': [], // Requires token only
  'POST /api/rbac/check-all-permissions': [], // Requires token only
  
  // Permission Management
  'GET /api/rbac/permissions': ['role_update'],
  'GET /api/rbac/permissions/granular': ['role_update'],
  'GET /api/rbac/permissions/:permissionName/dependencies': ['role_update'],
  'POST /api/rbac/permissions/validate': ['role_update'],
  'GET /api/rbac/pages/:pageName/dependencies': ['role_update'],
  'POST /api/rbac/permissions/multiple-dependencies': ['role_update'],
  
  // System Role Routes
  'GET /api/rbac/system-roles': ['role_update'],
  
  // Hostel-Specific Role Routes
  'GET /api/rbac/hostels/:hostelId/roles': ['role_read'],
  'POST /api/rbac/hostels/:hostelId/roles': ['role_update'],
  'PUT /api/rbac/hostels/:hostelId/roles/:roleId': ['role_update'],
  'DELETE /api/rbac/hostels/:hostelId/roles/:roleId': ['role_update'],
  
  // User Role Assignment
  'POST /api/rbac/hostels/:hostelId/users/:userId/assign-role': ['role_update'],

  // ========================================
  // STUDENT ROUTES (/api/student)
  // ========================================
  'GET /api/student/dashboard': ['view_dashboard'],
  'GET /api/student/profile': ['profile_read'],
  'PUT /api/student/profile': ['profile_update'],
  'GET /api/student/room': ['student_room_read'],
  'POST /api/student/complaints': ['complaint_create'],
  'GET /api/student/complaints': ['complaint_read'],
  'GET /api/student/complaints/:id': ['complaint_read'],
  'PUT /api/student/complaints/:id': ['complaint_update'],
  'DELETE /api/student/complaints/:id': ['complaint_delete'],
  'GET /api/student/visitor-logs': ['visitor_read'],
  'POST /api/student/visitor-logs': ['visitor_create'],
  'PUT /api/student/visitor-logs/:id': ['visitor_update'],
  'DELETE /api/student/visitor-logs/:id': ['visitor_delete'],
  'PUT /api/student/visitor-logs/:id/checkout': ['visitor_checkout'],

  // ========================================
  // SUPERADMIN ROUTES (/api/superadmin)
  // ========================================
  'POST /api/superadmin/login': [], // Public endpoint
  'GET /api/superadmin/dashboard': ['view_dashboard'],
  'GET /api/superadmin/billing-overview': ['billing_read'],
  'POST /api/superadmin/owners': ['owner_manage'],
  'POST /api/superadmin/hostels': ['hostel_global_manage'],
  'GET /api/superadmin/hostels': ['hostel_global_manage'],
  'GET /api/superadmin/hostels/:id': ['hostel_global_manage'],
  'GET /api/superadmin/hostels/:id/students': ['hostel_global_manage'],
  'PUT /api/superadmin/hostels/:id/plan': ['hostel_global_manage'],
  'PUT /api/superadmin/hostels/:id/status': ['hostel_global_manage'],
  'PUT /api/superadmin/hostels/:id/billing': ['billing_manage'],
  'DELETE /api/superadmin/hostels/:id': ['hostel_global_manage'],
  'GET /api/superadmin/hostels-by-region': ['system_stats_read']
};

/**
 * Get permissions required for a specific API endpoint
 * @param {string} method - HTTP method (GET, POST, PUT, DELETE, etc.)
 * @param {string} path - API path (e.g., '/api/hostels/:hostelId/students')
 * @returns {Array<string>} Array of required permission names
 */
function getApiPermissions(method, path) {
  const key = `${method.toUpperCase()} ${path}`;
  return API_PERMISSION_MAP[key] || [];
}

/**
 * Get all API endpoints that require a specific permission
 * @param {string} permission - Permission name
 * @returns {Array<string>} Array of API endpoint keys
 */
function getApisForPermission(permission) {
  return Object.keys(API_PERMISSION_MAP).filter(api => 
    API_PERMISSION_MAP[api].includes(permission)
  );
}

/**
 * Get all unique permissions used in the API
 * @returns {Array<string>} Array of unique permission names
 */
function getAllApiPermissions() {
  const permissions = new Set();
  Object.values(API_PERMISSION_MAP).forEach(apiPermissions => {
    apiPermissions.forEach(permission => permissions.add(permission));
  });
  return Array.from(permissions).sort();
}

/**
 * Get API endpoints grouped by permission category
 * @returns {Object} Object with permission categories as keys
 */
function getApisByCategory() {
  const categories = {
    'hostel_read': [],
    'room_read': [],
    'student_read': [],
    'complaint_read': [],
    'visitor_read': [],
    'warden_management': [],
    'staff_management': [],
    'rbac_management': [],
    'student_self_service': [],
    'superadmin_management': []
  };

  Object.entries(API_PERMISSION_MAP).forEach(([api, permissions]) => {
    if (api.includes('/hostels') && !api.includes('/rbac/')) {
      if (api.includes('/rooms')) {
        categories.room_management.push(api);
      } else if (api.includes('/students')) {
        categories.student_management.push(api);
      } else if (api.includes('/complaints')) {
        categories.complaint_management.push(api);
      } else if (api.includes('/visitors')) {
        categories.visitor_management.push(api);
      } else if (api.includes('/wardens')) {
        categories.warden_management.push(api);
      } else if (api.includes('/staff')) {
        categories.staff_management.push(api);
      } else {
        categories.hostel_management.push(api);
      }
    } else if (api.includes('/rbac/')) {
      categories.rbac_management.push(api);
    } else if (api.includes('/student/')) {
      categories.student_self_service.push(api);
    } else if (api.includes('/superadmin/')) {
      categories.superadmin_management.push(api);
    }
  });

  return categories;
}

module.exports = {
  API_PERMISSION_MAP,
  getApiPermissions,
  getApisForPermission,
  getAllApiPermissions,
  getApisByCategory
};
