/**
 * 🎯 PAGE API MAPPING
 *
 * This file contains the complete mapping of each owner dashboard page to the APIs it calls.
 * This is the foundation for intelligent page-level dependency resolution.
 *
 * Generated by analyzing all owner dashboard pages in the client/src/app/dashboard directory.
 */

const PAGE_API_MAP = {
  // ========================================
  // DASHBOARD PAGE (/dashboard/page.tsx)
  // ========================================
  dashboard: [
    // No direct API calls - this is a routing component
    // Uses context APIs only (useAuth, useHostel)
  ],

  // ========================================
  // MY HOSTELS PAGE (/dashboard/owner/hostels/page.tsx)
  // ========================================
  "my-hostels": [
    // Owner's hostels
    "GET /api/auth/hostels", // Get user's hostels
    "GET /api/superadmin/hostels", // Get all hostels (for superadmin)

    // Hostel CRUD operations
    "POST /api/hostels", // Create new hostel
    "PUT /api/hostels/:id", // Update hostel
    "DELETE /api/hostels/:id", // Delete hostel
    "GET /api/hostels/:id/stats", // Get hostel statistics
  ],

  // ========================================
  // STUDENTS PAGE (/dashboard/hostels/[hostelId]/students)
  // ========================================
  students: [
    // Main students list
    "GET /api/hostels/:hostelId/students",

    // Room allocation operations
    "GET /api/hostels/:hostelId/rooms", // For room allocation dropdown
    "POST /api/hostels/:hostelId/room-allocations", // For room allocation
    "DELETE /api/hostels/:hostelId/room-allocations/:allocationId", // For room deallocation

    // Student CRUD operations
    "POST /api/hostels/:hostelId/students", // Create student
    "PUT /api/hostels/:hostelId/students/:studentId", // Update student
    "DELETE /api/hostels/:hostelId/students/:studentId", // Delete student
  ],

  // ========================================
  // ROOMS PAGE (/dashboard/hostels/[hostelId]/rooms)
  // ========================================
  rooms: [
    // Main rooms list
    "GET /api/hostels/:hostelId/rooms",

    // Room CRUD operations
    "POST /api/hostels/:hostelId/rooms", // Create room
    "PUT /api/hostels/:hostelId/rooms/:roomId", // Update room
    "DELETE /api/hostels/:hostelId/rooms/:roomId", // Delete room

    // Room details and student management
    "GET /api/hostels/:hostelId/rooms/:roomId/students", // View students in room
    "DELETE /api/hostels/:hostelId/room-allocations/:studentId", // Remove student from room
  ],

  // ========================================
  // VISITORS PAGE (/dashboard/hostels/[hostelId]/visitors)
  // ========================================
  visitors: [
    // Main visitors list
    "GET /api/hostels/:hostelId/visitors",

    // Visitor CRUD operations
    "POST /api/hostels/:hostelId/visitors", // Create visitor
    "PUT /api/hostels/:hostelId/visitors/:visitorId", // Update visitor
    "DELETE /api/hostels/:hostelId/visitors/:visitorId", // Delete visitor

    // Visitor checkout
    "POST /api/hostels/:hostelId/visitors/:visitorId/checkout", // Checkout visitor

    // Student data for visitor creation (dependency)
    "GET /api/hostels/:hostelId/students", // Get students for visitor host selection
  ],

  // ========================================
  // COMPLAINTS PAGE (/dashboard/hostels/[hostelId]/complaints)
  // ========================================
  complaints: [
    // Main complaints list
    "GET /api/hostels/:hostelId/complaints",

    // Complaint management
    "PUT /api/hostels/:hostelId/complaints/:complaintId/status", // Update complaint status
    "POST /api/hostels/:hostelId/complaints/:complaintId/resolve", // Resolve complaint
    "DELETE /api/hostels/:hostelId/complaints/:complaintId", // Delete complaint (if implemented)
  ],

  // ========================================
  // WARDENS PAGE (/dashboard/hostels/[hostelId]/wardens)
  // ========================================
  wardens: [
    // Main wardens list
    "GET /api/hostels/:hostelId/wardens",

    // Warden CRUD operations
    "POST /api/hostels/:hostelId/wardens", // Create warden
    "PUT /api/hostels/:hostelId/wardens/:wardenId", // Update warden
    "DELETE /api/hostels/:hostelId/wardens/:wardenId", // Delete warden
  ],

  // ========================================
  // STAFF PAGE (/dashboard/hostels/[hostelId]/staff)
  // ========================================
  staff: [
    // Main staff list
    "GET /api/hostels/:hostelId/staff",

    // Staff CRUD operations
    "POST /api/hostels/:hostelId/staff", // Create staff
    "PUT /api/hostels/:hostelId/staff/:staffId", // Update staff
    "DELETE /api/hostels/:hostelId/staff/:staffId", // Delete staff
    "PATCH /api/hostels/:hostelId/staff/:staffId/status", // Toggle staff status

    // Role management (dependencies)
    "GET /api/rbac/hostels/:hostelId/roles", // Get available roles
    "POST /api/rbac/hostels/:hostelId/roles", // Create custom role
    "PUT /api/rbac/hostels/:hostelId/roles/:roleId", // Update role
    "DELETE /api/rbac/hostels/:hostelId/roles/:roleId", // Delete role
    "GET /api/rbac/permissions", // Get available permissions
    "POST /api/rbac/hostels/:hostelId/users/:userId/assign-role", // Assign role to user
  ],

  // ========================================
  // HOSTEL DASHBOARD (/dashboard/hostels/[hostelId])
  // ========================================
  "hostel-dashboard": [
    // Dashboard metrics
    "GET /api/hostels/:hostelId/dashboard", // Dashboard data
    "GET /api/hostels/:hostelId/stats", // Hostel statistics

    // Hostel management
    "GET /api/hostels/:hostelId", // Hostel details
    "PUT /api/hostels/:hostelId", // Update hostel
    "DELETE /api/hostels/:hostelId", // Delete hostel
  ],

  // ========================================
  // HOSTEL LIST (/dashboard/owner/hostels)
  // ========================================
  "hostel-list": [
    // Owner's hostels
    "GET /api/auth/hostels", // Get user's hostels
    "GET /api/auth/hostels/all", // Get all owner hostels

    // Hostel creation
    "POST /api/hostels", // Create new hostel
  ],

  // ========================================
  // BILLING PAGE (/dashboard/superadmin/billing)
  // ========================================
  billing: [
    // Billing overview and management
    "GET /api/superadmin/billing/overview", // Get billing overview
    "GET /api/superadmin/billing/revenue", // Get revenue data
    "GET /api/superadmin/billing/subscriptions", // Get subscription data
    "POST /api/superadmin/billing/generate-report", // Generate billing report
  ],

  // ========================================
  // REPORTS PAGE (/dashboard/superadmin/analytics)
  // ========================================
  reports: [
    // Analytics and reports
    "GET /api/superadmin/analytics/user-growth", // Get user growth data
    "GET /api/superadmin/analytics/hostel-growth", // Get hostel growth data
    "GET /api/superadmin/analytics/regional-distribution", // Get regional data
    "GET /api/superadmin/analytics/plan-distribution", // Get plan distribution (by plan_id)
    "POST /api/superadmin/analytics/export-report", // Export analytics report
  ],
};

/**
 * Get APIs required for a specific page
 * @param {string} pageName - The page name (e.g., 'students', 'rooms', 'visitors')
 * @returns {Array<string>} Array of API endpoints required by the page
 */
function getPageApis(pageName) {
  return PAGE_API_MAP[pageName] || [];
}

/**
 * Get all pages that use a specific API
 * @param {string} apiEndpoint - The API endpoint (e.g., 'GET /api/hostels/:hostelId/students')
 * @returns {Array<string>} Array of page names that use this API
 */
function getPagesForApi(apiEndpoint) {
  const pages = [];
  Object.entries(PAGE_API_MAP).forEach(([page, apis]) => {
    if (apis.includes(apiEndpoint)) {
      pages.push(page);
    }
  });
  return pages;
}

/**
 * Get all unique APIs used across all pages
 * @returns {Array<string>} Array of unique API endpoints
 */
function getAllPageApis() {
  const apis = new Set();
  Object.values(PAGE_API_MAP).forEach((pageApis) => {
    pageApis.forEach((api) => apis.add(api));
  });
  return Array.from(apis).sort();
}

/**
 * Get pages grouped by functionality
 * @returns {Object} Object with functionality groups as keys
 */
function getPagesByFunctionality() {
  return {
    student_read: ["students"],
    room_read: ["rooms"],
    visitor_read: ["visitors"],
    complaint_read: ["complaints"],
    staff_read: ["staff"],
    hostel_read: ["hostel-dashboard", "hostel-list"],
  };
}

/**
 * Analyze page dependencies based on API usage
 * @param {string} pageName - The page name
 * @returns {Object} Analysis of page dependencies
 */
function analyzePageDependencies(pageName) {
  const apis = getPageApis(pageName);
  const dependencies = {
    primaryApis: [],
    dependencyApis: [],
    crudOperations: [],
    crossPageDependencies: [],
  };

  apis.forEach((api) => {
    const [method, path] = api.split(" ");

    // Categorize APIs
    if (path.includes("/students") && !path.includes("/room-allocations")) {
      dependencies.primaryApis.push(api);
    } else if (path.includes("/room-allocations") || path.includes("/rooms")) {
      dependencies.dependencyApis.push(api);
    }

    // Identify CRUD operations
    if (["POST", "PUT", "DELETE"].includes(method)) {
      dependencies.crudOperations.push(api);
    }

    // Check for cross-page dependencies
    const otherPages = getPagesForApi(api);
    if (otherPages.length > 1) {
      dependencies.crossPageDependencies.push({
        api,
        sharedWith: otherPages.filter((p) => p !== pageName),
      });
    }
  });

  return dependencies;
}

module.exports = {
  PAGE_API_MAP,
  getPageApis,
  getPagesForApi,
  getAllPageApis,
  getPagesByFunctionality,
  analyzePageDependencies,
};
